### ISSUE TITLE
Site-ul `alegerilibere.ro` a fost închis, `www.alegerilibere.ro` încă mai merge

### ISSUE THREAD

**Issue by rxrdev** [RoTak00/aur-alegeri-libere-e-fake#1]
Noul endpoint este: `https://www.alegerilibere.ro/c.php`

https://github.com/RoTak00/aur-alegeri-libere-e-fake/blob/499b9016e92788e98b555c0286665338c9cd6d39/script.sh#L17

**Comment by rxrdev** [comment]
Update: l-au închis de tot.

**Comment by RoTak00** [comment]
Am actualizat repository-ul cu datele stranse pana la 1:03, cu o pauza de 40 de minute de la 23:54. Probabil a fost doar o schema de colectat adrese de e-mail. Urat.
